config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  authenticate :user do
    mount_carnival_at '/'
    resources :people
    resources :addresses
    resources :countries
    resources :states
    resources :cities
    resources :photos
    resources :phones
    resources :posts
    resources :post_files
    resources :tags
    resources :comments
    resources :blog

    get 'blog/:id/show_post' => 'blog#show_post', as: :show_post

    post 'phones/add_to_mob' => 'phones#add_to_mobile', as: :add_phone_to_mobile
    post 'phones/add_to_home' => 'phones#add_to_home', as: :add_phone_to_home
    post 'phones/add_all_to_mobile' => 'phones#add_all_to_mobile', as: :add_all_to_mobile
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  include Carnival::ModelHelper
  

  belongs_to :country
  belongs_to :state
  has_many :addresses
  has_many :people, :through => :addresses

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Carnival::ModelHelper
  
  belongs_to :post

end

app/models/person.rb
class Person < ActiveRecord::Base
  include Carnival::ModelHelper

  has_many :photos
  has_many :addresses
  has_many :phones, as: :phoneable

  accepts_nested_attributes_for :photos, :reject_if => lambda { |a| a[:image].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :addresses, :reject_if => lambda { |a| a[:address].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :phones, :reject_if => lambda { |a| a[:number].blank? }, :allow_destroy => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :person

  has_attached_file :image, styles: { medium: '640x480>', thumb: '160x120>'  }, default_url: 'missing.png'

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Carnival::ModelHelper
  
  has_attached_file :cover
  
  belongs_to :user
  has_many :comments
  has_many :post_files
  has_and_belongs_to_many :tags

  validates :cover, :title, presence: true
  validates_attachment :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  
  scope :to_tags, -> (tag_id){joins(:tags).where('tags.id' => tag_id)}

  accepts_nested_attributes_for :post_files, allow_destroy: true,
    reject_if: proc { |attributes| attributes['title'].blank? }

  accepts_nested_attributes_for :tags

  ACTIVE = 1
  INACTIVE = 2

  STATUS = {ACTIVE => "Active", INACTIVE => "Inactive" }

end

app/models/post_file.rb
class PostFile < ActiveRecord::Base
  include Carnival::ModelHelper
  
  belongs_to :post
  has_attached_file :file

  validates_attachment :file, :size => { :in => 0..10.kilobytes }

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  include Carnival::ModelHelper
  
  has_and_belongs_to_many :posts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_filter :load_data 

  def index
    if params[:tag].nil?
      @posts = Post.all
    else
      @posts = Post.to_tags(params[:tag])
    end
  end

  def show_post
    @post = Post.find(params[:id])
  end

  def load_data
  @tags = Tag.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < Carnival::BaseAdminController

  private

  def permitted_params
    params.permit(comment:[:comment, :approved])
  end
end

app/controllers/people_controller.rb
class PeopleController < Carnival::BaseAdminController

  private
  def permitted_params
    params.permit(person: [:name, :email, :bio, :birthday, 
                            photos_attributes:[:title, :image, :_destroy],
                            phones_attributes: [:phone_type_id, :number],
                            addresses_attributes: [:address, :number, :complement, :zipcode, :city_id, :state_id, :country_id, :address_type_id]
                          ])
  end
end

app/controllers/photos_controller.rb
class PhotosController < Carnival::BaseAdminController

  private
  def permitted_params
    params.permit(photo: [:title, :image, :user_id])
  end
end

app/controllers/post_files_controller.rb
class PostFilesController < Carnival::BaseAdminController


  private

  def permitted_params
    params.permit(:post_file[:file, :post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < Carnival::BaseAdminController

  private

  def permitted_params
    params.permit(post: [:title, :text, :status, :cover, :post_file_ids, :post_files_attributes => [:id, :post_file_ids, :_destroy, :file] ])
  end
end

app/controllers/tags_controller.rb
class TagsController < Carnival::BaseAdminController

  private

  def permitted_params
    params.permit(tag:[:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/_item.html.haml
%a{href: "#{show_post_path(id: post.id)}"}
  %img{alt: "", src: post.cover}
=link_to post.title, show_post_path(id: post.id)
=post.created_at.strftime('%d %b')

app/views/blog/index.html.haml
-@tags.each do |tag|
  = link_to tag.name, blog_index_path(tag: tag.id)



- @posts.each do |post|
  = render partial: 'item', locals: {post: post}
 

app/views/blog/show_post.html.haml
=@post.text.html_safe

app/views/carnival/_extra_header.html.haml
%div.sign_out= link_to t('logout'), destroy_user_session_path, :method => :delete
%div.salute
  = link_to "#" do
    .email
      = current_user.email
    %figure
      = image_tag "", :class => "default"

app/views/carnival/base_admin/home.html.haml
.container-fluid
  .row
    .col-md-12
      %h2 Welcome to Carnival Sample Application
      %p Carnival is an easy-to-use and extensible Rails Engine to speed up the development of data management interfaces.
      %p In this application you'll can view all of the potential Carnival Engine can give to you to create powerfull data application with a little bit of code, and with the full potential of already know Rails framework to go further with integrations and customizations, because you can easily customize and override Carnival features with standard Rails code so it's not necessary to learn a new syntax, framework or DSL.
      %p
        %a{href: "https://github.com/Vizir/carnival"}
          Fork Carnival on Github
        , 
        %a{href: "https://github.com/Vizir/carnival-sample-application"}
          Fork me on Github
  .row
    .col-md-12
      %h2 About the Sample Application
      %p We decided to implement a simple HRM (Human Resource Managemnet) application

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarnivalSampleApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>